-- AI Interviewer Schema Updates
-- Adds study_type, AI persona, interview sessions, conversation turns
-- Created: 2026-02-05

-- ============================================
-- 1. Update studies table
-- ============================================

-- Study type: how the AI conducts the interview
ALTER TABLE studies
ADD COLUMN study_type TEXT DEFAULT 'structured' NOT NULL
CHECK (study_type IN ('structured', 'streaming'));

COMMENT ON COLUMN studies.study_type IS 'Study type: structured (step-by-step questions) or streaming (natural conversation)';

-- AI persona prompt: generated by GPT-4o from study context, not user-authored
ALTER TABLE studies
ADD COLUMN ai_persona_prompt TEXT;

COMMENT ON COLUMN studies.ai_persona_prompt IS 'AI-generated interviewer persona prompt, stored after study setup';

-- Track when persona was last generated for staleness detection
ALTER TABLE studies
ADD COLUMN ai_persona_generated_at TIMESTAMPTZ;

COMMENT ON COLUMN studies.ai_persona_generated_at IS 'When the AI persona was last generated. Compare against updated_at to detect staleness.';

-- ============================================
-- 2. Update flow_sections table
-- ============================================

-- Time budget per section for streaming mode (auto-calculated, not user-editable)
ALTER TABLE flow_sections
ADD COLUMN time_limit_seconds INTEGER;

COMMENT ON COLUMN flow_sections.time_limit_seconds IS 'Auto-calculated time budget per section for streaming mode interviews';

-- ============================================
-- 3. Update flow_responses table
-- ============================================

ALTER TABLE flow_responses
ADD COLUMN turn_number INTEGER,
ADD COLUMN is_probe BOOLEAN DEFAULT false,
ADD COLUMN topic_tags TEXT[],
ADD COLUMN response_start_time TIMESTAMPTZ,
ADD COLUMN response_end_time TIMESTAMPTZ;

COMMENT ON COLUMN flow_responses.turn_number IS 'Conversation turn number within the interview';
COMMENT ON COLUMN flow_responses.is_probe IS 'Whether this response was to a follow-up probe question';
COMMENT ON COLUMN flow_responses.topic_tags IS 'AI-assigned topic tags for streaming mode analysis';

-- ============================================
-- 4. New table: interview_sessions
-- ============================================

CREATE TABLE interview_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  study_id UUID NOT NULL REFERENCES studies(id) ON DELETE CASCADE,
  participant_id UUID,

  -- Mode info (denormalized from study for query convenience)
  study_type TEXT NOT NULL CHECK (study_type IN ('structured', 'streaming')),
  interview_mode TEXT NOT NULL CHECK (interview_mode IN ('voice', 'video')),

  -- Session metadata
  started_at TIMESTAMPTZ DEFAULT NOW(),
  completed_at TIMESTAMPTZ,
  current_section_index INTEGER DEFAULT 0,
  current_item_index INTEGER DEFAULT 0,

  -- Recording
  recording_url TEXT,
  recording_duration_seconds INTEGER,

  -- Cost tracking
  elevenlabs_characters_used INTEGER DEFAULT 0,
  elevenlabs_cost_cents INTEGER DEFAULT 0,
  openai_input_tokens INTEGER DEFAULT 0,
  openai_output_tokens INTEGER DEFAULT 0,
  openai_cost_cents INTEGER DEFAULT 0,
  total_cost_cents INTEGER DEFAULT 0,

  -- Timing
  estimated_duration_seconds INTEGER,
  actual_duration_seconds INTEGER,
  duration_warning_shown BOOLEAN DEFAULT false,

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_interview_sessions_study ON interview_sessions(study_id);

-- RLS: Users can access sessions for their studies
ALTER TABLE interview_sessions ENABLE ROW LEVEL SECURITY;

CREATE POLICY interview_sessions_user_policy ON interview_sessions
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM studies
      WHERE studies.id = interview_sessions.study_id
      AND studies.user_id = auth.uid()
    )
  );

-- ============================================
-- 5. New table: conversation_turns
-- ============================================

CREATE TABLE conversation_turns (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id UUID NOT NULL REFERENCES interview_sessions(id) ON DELETE CASCADE,
  flow_item_id UUID REFERENCES flow_items(id) ON DELETE SET NULL,
  flow_section_id UUID REFERENCES flow_sections(id) ON DELETE SET NULL,

  turn_number INTEGER NOT NULL,
  speaker TEXT NOT NULL CHECK (speaker IN ('ai', 'participant')),

  -- Content
  text_content TEXT NOT NULL,
  audio_url TEXT,

  -- Timing
  started_at TIMESTAMPTZ NOT NULL,
  ended_at TIMESTAMPTZ,
  duration_seconds DECIMAL,

  -- AI metadata (for AI turns)
  is_probe BOOLEAN DEFAULT false,
  ai_decision_reasoning TEXT,

  -- Cost tracking (for AI turns)
  elevenlabs_characters INTEGER,
  openai_input_tokens INTEGER,
  openai_output_tokens INTEGER,

  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_conversation_turns_session ON conversation_turns(session_id);
CREATE INDEX idx_conversation_turns_flow_item ON conversation_turns(flow_item_id);

-- RLS: Users can access turns for their study sessions
ALTER TABLE conversation_turns ENABLE ROW LEVEL SECURITY;

CREATE POLICY conversation_turns_user_policy ON conversation_turns
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM interview_sessions
      JOIN studies ON studies.id = interview_sessions.study_id
      WHERE interview_sessions.id = conversation_turns.session_id
      AND studies.user_id = auth.uid()
    )
  );
