// ============================================
// UNDERCURRENT DATABASE TYPES
// TypeScript types matching the Supabase schema
// ============================================

// ============================================
// ENUM TYPES
// ============================================

export type StudyStatus =
  | 'draft'
  | 'ready_for_test'
  | 'tested'
  | 'live'
  | 'paused'
  | 'closed';

export type ProjectType = 
  | 'discovery'
  | 'concept_testing'
  | 'creative_testing'
  | 'brand_health';

export type VoiceType = 
  | 'preset'
  | 'cloned';

export type InterviewStatus = 
  | 'created'
  | 'in_progress'
  | 'completed'
  | 'failed';

export type JobStatus = 
  | 'queued'
  | 'running'
  | 'done'
  | 'failed';

export type JobType =
  | 'transcription'
  | 'synthesis'
  | 'voice_clone';

export type StudyType =
  | 'structured'
  | 'streaming';

export type InterviewMode =
  | 'voice'
  | 'video';

export type ConversationSpeaker =
  | 'ai'
  | 'participant';

// ============================================
// TABLE TYPES
// ============================================

export interface Study {
  id: string;
  user_id: string;
  title: string;
  status: StudyStatus;
  project_type: ProjectType | null;
  objective: string | null;
  topics: string[] | null;
  success_criteria: string | null;
  audience: string | null;
  guidelines: string | null;
  intro_text: string | null;
  brief_messages: BriefMessage[];
  voice_profile_id: string | null;
  // Step 1 Project Basics fields
  about_interviewer: string | null;
  language: string | null;
  // Interview mode settings (applies to entire study)
  interview_mode: InterviewMode;
  camera_required: boolean; // Only applies when interview_mode='video'
  // Study type: how the AI conducts the interview
  study_type: StudyType;
  // AI persona: generated by GPT-4o from study context, not user-authored
  ai_persona_prompt: string | null;
  ai_persona_generated_at: string | null;
  // ElevenLabs agent: created at publish time for streaming studies
  elevenlabs_agent_id: string | null;
  created_at: string;
  updated_at: string;
  published_at: string | null;
  closed_at: string | null;
}

export interface VoiceProfile {
  id: string;
  user_id: string;
  name: string;
  type: VoiceType;
  description: string | null;
  provider_voice_id: string | null;
  style_config: VoiceStyleConfig;
  samples_storage_paths: string[] | null;
  consent_confirmed: boolean;
  consent_confirmed_at: string | null;
  consent_owner_name: string | null;
  created_at: string;
  updated_at: string;
}

export interface InterviewGuide {
  id: string;
  study_id: string;
  sections: GuideSection[];
  approved_at: string | null;
  approved_by: string | null;
  created_at: string;
  updated_at: string;
}

export interface Interview {
  id: string;
  study_id: string;
  token: string;
  status: InterviewStatus;
  participant_name: string | null;
  participant_metadata: Record<string, unknown>;
  recording_path: string | null;
  transcript_path: string | null;
  transcript_text: string | null;
  started_at: string | null;
  completed_at: string | null;
  duration_seconds: number | null;
  is_test: boolean;
  metadata: InterviewMetadata;
  created_at: string;
  updated_at: string;
}

export interface Report {
  id: string;
  study_id: string;
  summary: string | null;
  insights: Insight[];
  share_token: string;
  is_public: boolean;
  generated_at: string | null;
  generation_metadata: Record<string, unknown>;
  created_at: string;
  updated_at: string;
}

export interface Job {
  id: string;
  type: JobType;
  payload: Record<string, unknown>;
  status: JobStatus;
  attempts: number;
  max_attempts: number;
  result: Record<string, unknown> | null;
  error_message: string | null;
  scheduled_for: string;
  started_at: string | null;
  completed_at: string | null;
  created_at: string;
  updated_at: string;
}

// ============================================
// STUDY FLOW TABLES (Step 2)
// ============================================

export type FlowItemType =
  | 'open_ended'
  | 'single_select'
  | 'multi_select'
  | 'rating_scale'
  | 'ranking'
  | 'instruction'
  | 'ai_conversation';

export interface StudyFlow {
  id: string;
  study_id: string;
  welcome_message: string;
  welcome_logo_url: string | null;
  created_at: string;
  updated_at: string;
}

export interface FlowSection {
  id: string;
  study_flow_id: string;
  title: string;
  display_order: number;
  stimulus_type: 'image' | 'website' | 'youtube' | null;
  stimulus_config: StimulusConfig | null;
  time_limit_seconds: number | null; // Auto-calculated time budget for streaming mode
  created_at: string;
  updated_at: string;
}

export interface StimulusConfig {
  url?: string;
  caption?: string;
  instructions?: string;
}

export interface FlowItem {
  id: string;
  section_id: string;
  item_type: FlowItemType;
  display_order: number;
  question_text: string | null;
  response_mode: 'voice' | 'text' | 'screen' | 'video' | null;
  item_config: FlowItemConfig;
  created_at: string;
  updated_at: string;
}

// Type-specific configurations
export interface OpenEndedConfig {
  probing_mode: 'disabled' | 'auto' | 'custom';
  custom_probes?: string[];
}

export interface SelectConfig {
  options: string[];
}

export interface RatingScaleConfig {
  scale_size: number; // 5-10
  low_label?: string;
  high_label?: string;
}

export interface RankingConfig {
  items: string[];
}

export interface InstructionConfig {
  content: string;
}

export interface AIConversationConfig {
  duration_seconds: number; // 30-300
  basis: 'prior_answers' | 'custom';
  custom_instructions?: string;
}

export type FlowItemConfig =
  | OpenEndedConfig
  | SelectConfig
  | RatingScaleConfig
  | RankingConfig
  | InstructionConfig
  | AIConversationConfig
  | Record<string, unknown>;

export interface FlowResponse {
  id: string;
  study_id: string;
  participant_id: string;
  flow_item_id: string;
  text_response: string | null;
  selected_options: string[] | null;
  rating_value: number | null;
  ranked_items: string[] | null;
  conversation_transcript: ConversationMessage[] | null;
  conversation_duration_seconds: number | null;
  response_metadata: ResponseMetadata | null;
  audio_url: string | null;
  // Video recording fields
  video_url: string | null;
  video_thumbnail_url: string | null;
  video_duration_seconds: number | null;
  video_format: string | null;
  video_resolution: string | null;
  video_start_timestamp: string | null;
  video_end_timestamp: string | null;
  video_start_offset_ms: number | null;
  video_end_offset_ms: number | null;
  // AI interviewer fields
  turn_number: number | null;
  is_probe: boolean;
  topic_tags: string[] | null;
  response_start_time: string | null;
  response_end_time: string | null;
  created_at: string;
}

export interface ConversationMessage {
  role: 'user' | 'assistant';
  content: string;
  timestamp: string;
}

export interface ResponseMetadata {
  sentiment?: string;
  themes?: string[];
  keywords?: string[];
  [key: string]: unknown;
}

// ============================================
// NESTED/JSONB TYPES
// ============================================

export interface BriefMessage {
  role: 'user' | 'assistant';
  content: string;
  timestamp: string;
}

export interface VoiceStyleConfig {
  tone?: 'warm' | 'neutral' | 'direct';
  pacing?: 'slow' | 'normal' | 'fast';
  dialect?: string;
  keyPhrases?: string[];
}

export interface GuideSection {
  id: string;
  title: string;
  questions: GuideQuestion[];
}

export interface GuideQuestion {
  id: string;
  text: string;
  probes: string[];
}

export interface InterviewMetadata {
  deviceType?: string;
  browser?: string;
  questionCount?: number;
  [key: string]: unknown;
}

export interface Insight {
  id: string;
  headline: string;
  description?: string;
  evidence: InsightEvidence[];
}

export interface InsightEvidence {
  quote: string;
  interviewId: string;
  timestamp?: number;
}

// ============================================
// INSERT/UPDATE TYPES
// ============================================

export type StudyInsert = Omit<Study, 'id' | 'created_at' | 'updated_at'>;
export type StudyUpdate = Partial<Omit<Study, 'id' | 'created_at' | 'updated_at'>>;

export type VoiceProfileInsert = Omit<VoiceProfile, 'id' | 'created_at' | 'updated_at'>;
export type VoiceProfileUpdate = Partial<Omit<VoiceProfile, 'id' | 'created_at' | 'updated_at'>>;

export type InterviewGuideInsert = Omit<InterviewGuide, 'id' | 'created_at' | 'updated_at'>;
export type InterviewGuideUpdate = Partial<Omit<InterviewGuide, 'id' | 'created_at' | 'updated_at'>>;

export type InterviewInsert = Omit<Interview, 'id' | 'token' | 'created_at' | 'updated_at'>;
export type InterviewUpdate = Partial<Omit<Interview, 'id' | 'token' | 'created_at' | 'updated_at'>>;

export type ReportInsert = Omit<Report, 'id' | 'share_token' | 'created_at' | 'updated_at'>;
export type ReportUpdate = Partial<Omit<Report, 'id' | 'share_token' | 'created_at' | 'updated_at'>>;

export type JobInsert = Omit<Job, 'id' | 'created_at' | 'updated_at'>;
export type JobUpdate = Partial<Omit<Job, 'id' | 'created_at' | 'updated_at'>>;

// Study Flow types
export type StudyFlowInsert = Omit<StudyFlow, 'id' | 'created_at' | 'updated_at'>;
export type StudyFlowUpdate = Partial<Omit<StudyFlow, 'id' | 'created_at' | 'updated_at'>>;

export type FlowSectionInsert = Omit<FlowSection, 'id' | 'created_at' | 'updated_at'>;
export type FlowSectionUpdate = Partial<Omit<FlowSection, 'id' | 'created_at' | 'updated_at'>>;

export type FlowItemInsert = Omit<FlowItem, 'id' | 'created_at' | 'updated_at'>;
export type FlowItemUpdate = Partial<Omit<FlowItem, 'id' | 'created_at' | 'updated_at'>>;

export type FlowResponseInsert = Omit<FlowResponse, 'id' | 'created_at'>;
export type FlowResponseUpdate = Partial<Omit<FlowResponse, 'id' | 'created_at'>>;

// ============================================
// QUERY RESULT TYPES (with relations)
// ============================================

export interface StudyWithRelations extends Study {
  voice_profile?: VoiceProfile | null;
  interview_guide?: InterviewGuide | null;
  study_flow?: StudyFlowWithSections | null;
  interviews?: Interview[];
  report?: Report | null;
}

// Study flow with nested sections and items
export interface StudyFlowWithSections extends StudyFlow {
  sections?: FlowSectionWithItems[];
}

export interface FlowSectionWithItems extends FlowSection {
  items?: FlowItem[];
}

export interface InterviewWithStudy extends Interview {
  study?: Study;
}

// ============================================
// DISTRIBUTION TABLE
// ============================================

export interface Distribution {
  id: string;
  study_id: string;
  name: string;
  shareable_link_id: string;
  max_responses: number | null;
  current_responses: number;
  redirect_completion_url: string | null;
  redirect_screenout_url: string | null;
  redirect_quota_full_url: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export type DistributionInsert = Omit<Distribution, 'id' | 'shareable_link_id' | 'current_responses' | 'created_at' | 'updated_at'>;
export type DistributionUpdate = Partial<Pick<Distribution, 'name' | 'max_responses' | 'redirect_completion_url' | 'redirect_screenout_url' | 'redirect_quota_full_url'>>;

export interface StudyWithDistribution extends Study {
  distributions?: Distribution[];
}

// ============================================
// INTERVIEW SESSION & CONVERSATION TURNS
// ============================================

export type ReviewStatus = 'pending' | 'accepted' | 'rejected';

export interface AISummary {
  bullets: string[];
  generated_at: string;
  model: string;
}

export interface InterviewSession {
  id: string;
  study_id: string;
  participant_id: string | null;
  study_type: StudyType;
  interview_mode: InterviewMode;
  started_at: string | null;
  completed_at: string | null;
  current_section_index: number;
  current_item_index: number;
  recording_url: string | null;
  recording_duration_seconds: number | null;
  // Participant info
  participant_name: string | null;
  participant_email: string | null;
  participant_metadata: Record<string, unknown>;
  // Review
  review_status: ReviewStatus;
  ai_summary: AISummary | null;
  language: string | null;
  // Cost tracking
  elevenlabs_characters_used: number;
  elevenlabs_cost_cents: number;
  openai_input_tokens: number;
  openai_output_tokens: number;
  openai_cost_cents: number;
  total_cost_cents: number;
  // Timing
  estimated_duration_seconds: number | null;
  actual_duration_seconds: number | null;
  duration_warning_shown: boolean;
  created_at: string;
  updated_at: string;
}

export interface ConversationTurn {
  id: string;
  session_id: string;
  flow_item_id: string | null;
  flow_section_id: string | null;
  turn_number: number;
  speaker: ConversationSpeaker;
  text_content: string;
  audio_url: string | null;
  started_at: string;
  ended_at: string | null;
  duration_seconds: number | null;
  is_probe: boolean;
  ai_decision_reasoning: string | null;
  elevenlabs_characters: number | null;
  openai_input_tokens: number | null;
  openai_output_tokens: number | null;
  created_at: string;
}

// ============================================
// SCREENER TABLES
// ============================================

export type ScreenerQuestionType = 'single_select' | 'multi_select' | 'text';

export interface ScreenerQuestion {
  id: string;
  study_id: string;
  question_text: string;
  question_type: ScreenerQuestionType;
  options: string[];
  qualifying_answers: string[];
  display_order: number;
  is_required: boolean;
  created_at: string;
  updated_at: string;
}

export interface ScreenerResponse {
  id: string;
  session_id: string;
  screener_question_id: string;
  answer: string;
  passed: boolean;
  created_at: string;
}

export type ScreenerQuestionInsert = Omit<ScreenerQuestion, 'id' | 'created_at' | 'updated_at'>;
export type ScreenerQuestionUpdate = Partial<Omit<ScreenerQuestion, 'id' | 'created_at' | 'updated_at'>>;

export type ScreenerResponseInsert = Omit<ScreenerResponse, 'id' | 'created_at'>;

export type InterviewSessionInsert = Omit<InterviewSession, 'id' | 'created_at' | 'updated_at'>;
export type InterviewSessionUpdate = Partial<Omit<InterviewSession, 'id' | 'created_at' | 'updated_at'>>;

export type ConversationTurnInsert = Omit<ConversationTurn, 'id' | 'created_at'>;
export type ConversationTurnUpdate = Partial<Omit<ConversationTurn, 'id' | 'created_at'>>;

